### ISSUE TITLE
Yamux v2.1.0 broke libp2p compat

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-yamux#36]
It introduces a new `InitialStreamWindowSize` config entry to set the initial stream window size. Unfortunately:

1. This (and `MaxStreamWindowSize`) affect both our receive windows _and_ our initial send window.
2. This _isn't_ something that we negotiate anywhere.
3. If a peer has an initial send window that's too high, the peer will disconnect due to protocol violation.

This affects us here because this library sets the `MaxStreamWindowSize` to 16MiB. That means, before we updated to Yamux v2.1.0, the initial send & receive window was 16MiB. After v2.1.0, this is the _max_ window and the initial one is set to `InitialStreamWindowSize` (16KiB). That means an _old_ libp2p node will try to send up to 16MiB of data, while a new node will reset the stream after 16KiB.

1. It sounds like we need to set the `InitialStreamWindowSize` to 16MiB. This is... unfortunate, but not terrible.
2. We might as well increase the maximum window size...

In the future, it would be nice to have a protocol extension where both sides could try to raise the initial stream window size.

Also note: I attempted to fix this issue by setting `InitialStreamWindowSize` to 16MiB but something still didn't work... I'm not sure what, but there needs to be more investigation (cc @dirkmc)

Testing: This _should_ have been caught by tests. Why not? Well:

1. We're adjusting defaults _here_ instead of setting them down in go-yamux. That means our go-yamux tests won't catch issues here.
2. ~I have _no_ idea why this isn't showing up in our other tests, but the likely answer is that we're just sending around really small files/blocks. We need better stress tests.~
3. We're not performing interop tests here. We _do_ have interop tests, but they're all mplex based and only work go<->js.

**Comment by Stebalien** [comment]
- [x] @marten-seemann could you handle this?
- [ ] @mxinden let's confirm rust & go agree here on window sizes... I don't think we ever considered these important in the past.
- [ ] @vasco-santos could you confirm the same for js-libp2p?

**Comment by marten-seemann** [comment]
@Stebalien Where do the 16 MB come from? Our [spec](https://github.com/libp2p/go-yamux/blob/master/spec.md) says it's 256 kB, and I think this is the commit that change the default: https://github.com/libp2p/go-yamux/commit/f6e177c8572c46dd6e318f12de23afa79a22f17f.

The fix is easy: Just revert that change to the constant, and add a big fat warning that this is a value taken from the spec, not an implementation choice.

> Testing: This should have been caught by tests.

I fully agree. We should have something similar to the [quic-transport interop tests](https://github.com/libp2p/go-libp2p-quic-transport/blob/master/.github/workflows/interop.yml) here.

**Comment by Stebalien** [comment]
I bumped it to 1MiB in 2018, Vyzo bumped it to 16MiB in 2019... I'm a bit concerned that 256KiB will break it in practice.

**Comment by Stebalien** [comment]
We could pull a "liberal on the inputs" kind of thing. I.e., set the initial _send_ window size to 256KiB (seems like the safest) but set the initial _receive_ window to 1MiB (or 16...). After some time, we can lower the initial receive window.

Basically, the _send_ window is the only part that really matters.

**Comment by marten-seemann** [comment]
> I bumped it to 1MiB in 2018, Vyzo bumped it to 16MiB in 2019...

Are you referring to the `config.MaxStreamWindowSize`? That's the size we'd use for the first window update.

We initialized the window to 256 kB in v2.0.0: https://github.com/libp2p/go-yamux/blob/b6118a4b2a9b3038a0da9f29d4670b718f6850e2/stream.go#L51-L66

**Comment by Stebalien** [comment]
Oh, oh that makes me feel so much better. Yeah, then we just need to make this non-configurable and set it to 256KiB.

Note: I _would_ like to make it _somewhat_ configurable. If it's not too hard, it would be nice to send an immediate update on opening a stream that sets it to some higher minimum. But that's not critical.

**Comment by Stebalien** [comment]
That would explain:

> Also note: I attempted to fix this issue by setting InitialStreamWindowSize to 16MiB but something still didn't work... I'm not sure what, but there needs to be more investigation...

Streams going the _other_ way likely had problems.

**Comment by vasco-santos** [comment]
> could you confirm the same for js-libp2p?

we do not have yamux support in js, but thanks for pinging

**Comment by mxinden** [comment]
>  @mxinden let's confirm rust & go agree here on window sizes... I don't think we ever considered these important in the past.

Initial window size: [`rust-yamux` follows](https://github.com/libp2p/rust-yamux/blob/develop/src/lib.rs#L41) the [spec value of 256KB](https://github.com/hashicorp/yamux/blob/master/spec.md#flow-control).

Maximum window size: `rust-yamux` does not enforce a maximum window size.


> I bumped it to 1MiB in 2018, Vyzo bumped it to 16MiB in 2019... I'm a bit concerned that 256KiB will break it in practice.

@Stebalien may I ask what the motivation for these large stream windows were? Setting a large window per stream defeats the purpose of flow control on the multiplexing layer. While a large window may increase bandwidth, the same bandwidth can be achieved with early window update messages (see https://github.com/libp2p/rust-yamux/issues/100 in general and the concrete [benchmarks](https://github.com/libp2p/rust-yamux/issues/100#issuecomment-774461550) in specific) on most [bandwitdth-delay](https://en.wikipedia.org/wiki/Bandwidth-delay_product) environments with the latter still enforcing flow control on the multiplexing layer.

**Comment by mxinden** [comment]
>  @mxinden let's confirm rust & go agree here on window sizes...

- Initial window size: [`rust-yamux` follows](https://github.com/libp2p/rust-yamux/blob/develop/src/lib.rs#L41) the [spec value of 256KB](https://github.com/hashicorp/yamux/blob/master/spec.md#flow-control).

- Maximum window size: `rust-yamux` does not enforce a maximum window size as a sender. Thus, if a receiver chooses to send a large window update  (e.g. 16MB) `rust-yamux` [happily adds the additional credit on top of the existing credit](https://github.com/libp2p/rust-yamux/blob/e2368ec9617de40e46dc7b8535421377044f38bf/src/connection.rs#L818). As a receiver `rust-yamux` uses the initial window size (256KB) and sends window update messages once the sender depleted half or more of the window. See https://github.com/libp2p/rust-yamux/issues/100 for an in-depth analysis of sending the window update early as a receiver.

- Maximum data frame size: `rust-yamux` [by default splits data frames larger than 16KB](https://github.com/libp2p/rust-yamux/blob/develop/src/lib.rs#L43-L57) before sending to allow interleaving of control frames such as window updates and thus improve throughput.  See [benchmarks](https://github.com/libp2p/rust-yamux/issues/100#issuecomment-776883593) and  [corresponding pull request](https://github.com/libp2p/rust-yamux/pull/111). `rust-yamux` does not restrict the size of individual data frames when receiving (other than the usual window size enforcement).

---

>  I don't think we ever considered these important in the past.

Mostly agree. Only thing I remember is back in 2020 where Toralf discovered that `rust-yamux`  was incompatible with `go-yamux` in regards to window updates. The corresponding fixes have been rolled out.

> This crate understands the initial window update as the total receive window size whereas go-yamux adds the window update to the implicit default of 256 KiB. 

https://github.com/libp2p/rust-yamux/issues/92

---

As far as I know `rust-yamux` is fully compatible with `go-yamux` `< v2.1.0`. With https://github.com/libp2p/go-yamux/pull/57 the two (`rust-yamux` and `go-yamux`) should be fully compatible again.

@Stebalien @marten-seemann please correct me in case I am missing something.

**Comment by Stebalien** [comment]
> Maximum window size: rust-yamux does not enforce a maximum window size as a sender. Thus, if a receiver chooses to send a large window update (e.g. 16MB) rust-yamux happily adds the additional credit on top of the existing credit. As a receiver rust-yamux uses the initial window size (256KB) and sends window update messages once the sender depleted half or more of the window. See libp2p/rust-yamux#100 for an in-depth analysis of sending the window update early as a receiver.

This matches what go does now (after the bug was fixed) and did before the bug was introduced.

> Maximum data frame size: rust-yamux by default splits data frames larger than 16KB before sending to allow interleaving of control frames such as window updates and thus improve throughput. See benchmarks and corresponding pull request. rust-yamux does not restrict the size of individual data frames when receiving (other than the usual window size enforcement).


Interesting. Go splits at 64KiB (configurable). Although we never really benchmarked it.
